INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 1, 1, 'Silver', 'A9');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 2, 1, 'Silver', 'B9');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 3, 1, 'Silver', 'C9');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D9');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D10');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D11');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 4, 1, 'Gold', 'D12');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E9');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E10');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E11');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 5, 1, 'Gold', 'E12');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F9');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F10');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F11');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 6, 1, 'Gold', 'F12');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G9');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G10');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G11');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 7, 1, 'Gold', 'G12');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H9');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H10');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H11');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 8, 1, 'Gold', 'H12');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I9');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I10');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I11');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 9, 1, 'Gold', 'I12');

INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J1');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J2');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J3');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J4');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J5');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J6');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J7');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J8');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J9');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J10');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J11');
INSERT INTO public.seat( row, screen_id, category, seat_no) VALUES ( 10, 1, 'Gold', 'J12');

INSERT INTO public.show(show_id, duration, movie_name, screen_id, start_time, theater_name) VALUES (1, 9000, 'Shang-Chi and The Legend of the Ten Rings', 1, '2021-11-07 09:15:00', 'PVR Mumbai');
INSERT INTO public.show(show_id, duration, movie_name, screen_id, start_time, theater_name) VALUES (2, 9000, 'Shang-Chi and The Legend of the Ten Rings', 1, '2021-11-07 12:15:00', 'PVR Mumbai');
INSERT INTO public.show(show_id, duration, movie_name, screen_id, start_time, theater_name) VALUES (3, 9000, 'Shang-Chi and The Legend of the Ten Rings', 1, '2021-11-07 15:15:00', 'PVR Mumbai');
INSERT INTO public.show(show_id, duration, movie_name, screen_id, start_time, theater_name) VALUES (4, 9000, 'Shang-Chi and The Legend of the Ten Rings', 1, '2021-11-07 16:15:00', 'PVR Mumbai');